### ISSUE TITLE
submit hw7 

### ISSUE THREAD

**Issue by akothapa** [AmherstCollege/STAT495-Kothapalli-public#2]
Professor Horton,
Fei & I will be working together on this homework.

**Comment by akothapa** [comment]
Dear Professor Horton, 
The app cannot run online, but it runs perfectly locally. (I published it to https://akothapa.shinyapps.io/emilydickinsonapp but there is a constant "cannot open the connection" error.)

**Comment by nicholasjhorton** [comment]
I'm not seeing this in github: can you please make the files available so that I can test?

Thanks in advance,

Nick

> On Nov 11, 2015, at 6:58 PM, akothapa <notifications@github.com> wrote:
> 
> Dear Professor Horton, 
> The app cannot run online, but it runs perfectly locally. (I published it to https://akothapa.shinyapps.io/emilydickinsonapp but there is a constant "cannot open the connection" error.)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by akothapa** [comment]
Professor Horton, Thank you so much for all of your help! Everything is up and running!

The link to our application:
https://akothapa.shinyapps.io/emilydickinsonapp
